### 
POST http://localhost:3000/api/getAllUsers
content-type: application/json

### 
POST http://localhost:3000/api/signup
content-type: application/json

{
    "user": "user1",
    "password": "pass123"
}


### 
POST http://localhost:3000/api/login
content-type: application/json

{
    "user": "user1",
    "password": "pass12345"
}


### 
POST http://localhost:3000/api/logout
content-type: application/json

{
    "user": "user1",
    "session": "0x2F1639B56EC16857d33a9D468618aE66Bf02b592"
}
